# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from internal.policy.ml.proto import dlp_inference_pb2 as internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in internal/policy/ml/proto/dlp_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DLPInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectSensitiveInfo = channel.unary_unary(
                '/dlp_inference.DLPInference/DetectSensitiveInfo',
                request_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoRequest.SerializeToString,
                response_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoResponse.FromString,
                _registered_method=True)
        self.BatchDetectSensitiveInfo = channel.unary_unary(
                '/dlp_inference.DLPInference/BatchDetectSensitiveInfo',
                request_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoRequest.SerializeToString,
                response_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/dlp_inference.DLPInference/HealthCheck',
                request_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class DLPInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectSensitiveInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDetectSensitiveInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DLPInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectSensitiveInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSensitiveInfo,
                    request_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoRequest.FromString,
                    response_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoResponse.SerializeToString,
            ),
            'BatchDetectSensitiveInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDetectSensitiveInfo,
                    request_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoRequest.FromString,
                    response_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckRequest.FromString,
                    response_serializer=internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dlp_inference.DLPInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dlp_inference.DLPInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DLPInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectSensitiveInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dlp_inference.DLPInference/DetectSensitiveInfo',
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoRequest.SerializeToString,
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.SensitiveInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDetectSensitiveInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dlp_inference.DLPInference/BatchDetectSensitiveInfo',
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoRequest.SerializeToString,
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.BatchSensitiveInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dlp_inference.DLPInference/HealthCheck',
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckRequest.SerializeToString,
            internal_dot_policy_dot_ml_dot_proto_dot_dlp__inference__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
