// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: cursor-grpc/server_stream.proto

package cursor_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetHardLimit_FullMethodName = "/aiserver.v1.DashboardService/GetHardLimit"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Service Definition ---
type DashboardServiceClient interface {
	// RPC method to get the hard usage limits
	GetHardLimit(ctx context.Context, in *GetHardLimitRequest, opts ...grpc.CallOption) (*GetHardLimitResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetHardLimit(ctx context.Context, in *GetHardLimitRequest, opts ...grpc.CallOption) (*GetHardLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHardLimitResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetHardLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
//
// --- Service Definition ---
type DashboardServiceServer interface {
	// RPC method to get the hard usage limits
	GetHardLimit(context.Context, *GetHardLimitRequest) (*GetHardLimitResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetHardLimit(context.Context, *GetHardLimitRequest) (*GetHardLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHardLimit not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetHardLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHardLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetHardLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetHardLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetHardLimit(ctx, req.(*GetHardLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiserver.v1.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHardLimit",
			Handler:    _DashboardService_GetHardLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cursor-grpc/server_stream.proto",
}

const (
	UnifiedChatService_StreamUnifiedChatWithToolsSSE_FullMethodName = "/aiserver.v1.UnifiedChatService/StreamUnifiedChatWithToolsSSE"
)

// UnifiedChatServiceClient is the client API for UnifiedChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnifiedChatServiceClient interface {
	// Assuming SSE implies server-streaming, but keeping request stream for flexibility
	// If it's truly just SSE server->client, change request to non-stream
	StreamUnifiedChatWithToolsSSE(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse], error)
}

type unifiedChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnifiedChatServiceClient(cc grpc.ClientConnInterface) UnifiedChatServiceClient {
	return &unifiedChatServiceClient{cc}
}

func (c *unifiedChatServiceClient) StreamUnifiedChatWithToolsSSE(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UnifiedChatService_ServiceDesc.Streams[0], UnifiedChatService_StreamUnifiedChatWithToolsSSE_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UnifiedChatService_StreamUnifiedChatWithToolsSSEClient = grpc.BidiStreamingClient[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]

// UnifiedChatServiceServer is the server API for UnifiedChatService service.
// All implementations must embed UnimplementedUnifiedChatServiceServer
// for forward compatibility.
type UnifiedChatServiceServer interface {
	// Assuming SSE implies server-streaming, but keeping request stream for flexibility
	// If it's truly just SSE server->client, change request to non-stream
	StreamUnifiedChatWithToolsSSE(grpc.BidiStreamingServer[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]) error
	mustEmbedUnimplementedUnifiedChatServiceServer()
}

// UnimplementedUnifiedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnifiedChatServiceServer struct{}

func (UnimplementedUnifiedChatServiceServer) StreamUnifiedChatWithToolsSSE(grpc.BidiStreamingServer[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUnifiedChatWithToolsSSE not implemented")
}
func (UnimplementedUnifiedChatServiceServer) mustEmbedUnimplementedUnifiedChatServiceServer() {}
func (UnimplementedUnifiedChatServiceServer) testEmbeddedByValue()                            {}

// UnsafeUnifiedChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnifiedChatServiceServer will
// result in compilation errors.
type UnsafeUnifiedChatServiceServer interface {
	mustEmbedUnimplementedUnifiedChatServiceServer()
}

func RegisterUnifiedChatServiceServer(s grpc.ServiceRegistrar, srv UnifiedChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedUnifiedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnifiedChatService_ServiceDesc, srv)
}

func _UnifiedChatService_StreamUnifiedChatWithToolsSSE_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UnifiedChatServiceServer).StreamUnifiedChatWithToolsSSE(&grpc.GenericServerStream[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UnifiedChatService_StreamUnifiedChatWithToolsSSEServer = grpc.BidiStreamingServer[StreamUnifiedChatWithToolsRequest, StreamUnifiedChatWithToolsResponse]

// UnifiedChatService_ServiceDesc is the grpc.ServiceDesc for UnifiedChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnifiedChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiserver.v1.UnifiedChatService",
	HandlerType: (*UnifiedChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUnifiedChatWithToolsSSE",
			Handler:       _UnifiedChatService_StreamUnifiedChatWithToolsSSE_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cursor-grpc/server_stream.proto",
}
