// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cursor-grpc/server_stream.proto

package cursor_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopReason int32

const (
	StopReason_STOP_REASON_UNSPECIFIED StopReason = 0
	StopReason_STOP_SEQUENCE           StopReason = 1
	StopReason_MAX_TOKENS              StopReason = 2
	StopReason_TOOL_USE                StopReason = 3
	StopReason_CONTENT_FILTERED        StopReason = 4
	StopReason_OTHER                   StopReason = 5
)

// Enum value maps for StopReason.
var (
	StopReason_name = map[int32]string{
		0: "STOP_REASON_UNSPECIFIED",
		1: "STOP_SEQUENCE",
		2: "MAX_TOKENS",
		3: "TOOL_USE",
		4: "CONTENT_FILTERED",
		5: "OTHER",
	}
	StopReason_value = map[string]int32{
		"STOP_REASON_UNSPECIFIED": 0,
		"STOP_SEQUENCE":           1,
		"MAX_TOKENS":              2,
		"TOOL_USE":                3,
		"CONTENT_FILTERED":        4,
		"OTHER":                   5,
	}
)

func (x StopReason) Enum() *StopReason {
	p := new(StopReason)
	*p = x
	return p
}

func (x StopReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopReason) Descriptor() protoreflect.EnumDescriptor {
	return file_cursor_grpc_server_stream_proto_enumTypes[0].Descriptor()
}

func (StopReason) Type() protoreflect.EnumType {
	return &file_cursor_grpc_server_stream_proto_enumTypes[0]
}

func (x StopReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopReason.Descriptor instead.
func (StopReason) EnumDescriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_USER             Role = 1
	Role_ASSISTANT        Role = 2
	Role_TOOL             Role = 3
	Role_SYSTEM           Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "USER",
		2: "ASSISTANT",
		3: "TOOL",
		4: "SYSTEM",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"USER":             1,
		"ASSISTANT":        2,
		"TOOL":             3,
		"SYSTEM":           4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_cursor_grpc_server_stream_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_cursor_grpc_server_stream_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{1}
}

// Request message for the GetHardLimit RPC
type GetHardLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: The ID of the team for which to retrieve the limit.
	// If omitted, might return the limit for the current user or a default.
	// T: 5 likely maps to int32 or uint32. opt:!0 makes it optional.
	TeamId        *int32 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHardLimitRequest) Reset() {
	*x = GetHardLimitRequest{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHardLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardLimitRequest) ProtoMessage() {}

func (x *GetHardLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardLimitRequest.ProtoReflect.Descriptor instead.
func (*GetHardLimitRequest) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{0}
}

func (x *GetHardLimitRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

// Response message for the GetHardLimit RPC
type GetHardLimitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary hard limit value (e.g., request count, token count).
	// T: 5 likely maps to int32 or uint32.
	HardLimit int32 `protobuf:"varint,1,opt,name=hard_limit,json=hardLimit,proto3" json:"hard_limit,omitempty"`
	// Flag indicating if usage beyond the hard limit (potentially paid)
	// is disallowed.
	// T: 8 maps to bool.
	NoUsageBasedAllowed bool `protobuf:"varint,2,opt,name=no_usage_based_allowed,json=noUsageBasedAllowed,proto3" json:"no_usage_based_allowed,omitempty"`
	// A separate hard limit applied on a per-user basis within a team.
	// T: 5 likely maps to int32 or uint32.
	HardLimitPerUser int32 `protobuf:"varint,3,opt,name=hard_limit_per_user,json=hardLimitPerUser,proto3" json:"hard_limit_per_user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHardLimitResponse) Reset() {
	*x = GetHardLimitResponse{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHardLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardLimitResponse) ProtoMessage() {}

func (x *GetHardLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardLimitResponse.ProtoReflect.Descriptor instead.
func (*GetHardLimitResponse) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{1}
}

func (x *GetHardLimitResponse) GetHardLimit() int32 {
	if x != nil {
		return x.HardLimit
	}
	return 0
}

func (x *GetHardLimitResponse) GetNoUsageBasedAllowed() bool {
	if x != nil {
		return x.NoUsageBasedAllowed
	}
	return false
}

func (x *GetHardLimitResponse) GetHardLimitPerUser() int32 {
	if x != nil {
		return x.HardLimitPerUser
	}
	return 0
}

// Matches the framing observed: contains one part per message
type StreamUnifiedChatWithToolsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Potential common fields like sequence number could go here (e.g., int64 seq_no = 1;)
	Part          *ResponsePart `protobuf:"bytes,2,opt,name=part,proto3" json:"part,omitempty"` // Field #2 consistently holds the main payload part
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUnifiedChatWithToolsResponse) Reset() {
	*x = StreamUnifiedChatWithToolsResponse{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUnifiedChatWithToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUnifiedChatWithToolsResponse) ProtoMessage() {}

func (x *StreamUnifiedChatWithToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUnifiedChatWithToolsResponse.ProtoReflect.Descriptor instead.
func (*StreamUnifiedChatWithToolsResponse) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamUnifiedChatWithToolsResponse) GetPart() *ResponsePart {
	if x != nil {
		return x.Part
	}
	return nil
}

// Represents one chunk/part of the response stream payload
type ResponsePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A oneof seems most likely given the different field numbers observed
	// inside the Field #2 payload of the outer message.
	//
	// Types that are valid to be assigned to Content:
	//
	//	*ResponsePart_MetadataMarker
	//	*ResponsePart_BubbleId
	//	*ResponsePart_MessagePart
	//	*ResponsePart_ToolCall
	//	*ResponsePart_FinalResponse
	//	*ResponsePart_ErrorDetails
	Content       isResponsePart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePart) Reset() {
	*x = ResponsePart{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePart) ProtoMessage() {}

func (x *ResponsePart) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePart.ProtoReflect.Descriptor instead.
func (*ResponsePart) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ResponsePart) GetContent() isResponsePart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ResponsePart) GetMetadataMarker() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_MetadataMarker); ok {
			return x.MetadataMarker
		}
	}
	return nil
}

func (x *ResponsePart) GetBubbleId() string {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_BubbleId); ok {
			return x.BubbleId
		}
	}
	return ""
}

func (x *ResponsePart) GetMessagePart() *ContentPart {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_MessagePart); ok {
			return x.MessagePart
		}
	}
	return nil
}

func (x *ResponsePart) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ResponsePart) GetFinalResponse() *FinalResponse {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_FinalResponse); ok {
			return x.FinalResponse
		}
	}
	return nil
}

func (x *ResponsePart) GetErrorDetails() *ErrorDetails {
	if x != nil {
		if x, ok := x.Content.(*ResponsePart_ErrorDetails); ok {
			return x.ErrorDetails
		}
	}
	return nil
}

type isResponsePart_Content interface {
	isResponsePart_Content()
}

type ResponsePart_MetadataMarker struct {
	// Field #23: Seen with zero length payload. Maybe metadata, marker, or start/end signal?
	MetadataMarker *emptypb.Empty `protobuf:"bytes,23,opt,name=metadata_marker,json=metadataMarker,proto3,oneof"` // Placeholder name
}

type ResponsePart_BubbleId struct {
	// Field #27: Seen with a UUID-like string. Could be an ID for the chunk or bubble.
	BubbleId string `protobuf:"bytes,27,opt,name=bubble_id,json=bubbleId,proto3,oneof"` // Or chunk_id
}

type ResponsePart_MessagePart struct {
	// Field #25: Seen with nested message containing text and other data. Most likely content.
	MessagePart *ContentPart `protobuf:"bytes,25,opt,name=message_part,json=messagePart,proto3,oneof"`
}

type ResponsePart_ToolCall struct {
	// Other potential parts based on service capabilities (e.g., tool calls)
	ToolCall *ToolCall `protobuf:"bytes,26,opt,name=tool_call,json=toolCall,proto3,oneof"` // Example: If tool calls use field 26
}

type ResponsePart_FinalResponse struct {
	FinalResponse *FinalResponse `protobuf:"bytes,28,opt,name=final_response,json=finalResponse,proto3,oneof"` // Example: If final response uses field 28
}

type ResponsePart_ErrorDetails struct {
	ErrorDetails *ErrorDetails `protobuf:"bytes,29,opt,name=error_details,json=errorDetails,proto3,oneof"` // Example: If error uses field 29
}

func (*ResponsePart_MetadataMarker) isResponsePart_Content() {}

func (*ResponsePart_BubbleId) isResponsePart_Content() {}

func (*ResponsePart_MessagePart) isResponsePart_Content() {}

func (*ResponsePart_ToolCall) isResponsePart_Content() {}

func (*ResponsePart_FinalResponse) isResponsePart_Content() {}

func (*ResponsePart_ErrorDetails) isResponsePart_Content() {}

// Corresponds to the nested message seen within Field #25
type ContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // Field #1 seen with text
	// Field #2 seen with base64-like data. Could be metadata, citations, etc.
	// Using Struct for flexibility until its exact nature is known.
	Metadata      *structpb.Struct `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // Or 'citations', 'related_data' etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{4}
}

func (x *ContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentPart) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Represents a tool call requested by the model (Example structure for field 26)
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// Represents the final response details (Example structure for field 28)
type FinalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopReason    StopReason             `protobuf:"varint,1,opt,name=stop_reason,json=stopReason,proto3,enum=aiserver.v1.StopReason" json:"stop_reason,omitempty"`
	UsageMetadata *UsageMetadata         `protobuf:"bytes,2,opt,name=usage_metadata,json=usageMetadata,proto3" json:"usage_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalResponse) Reset() {
	*x = FinalResponse{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResponse) ProtoMessage() {}

func (x *FinalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResponse.ProtoReflect.Descriptor instead.
func (*FinalResponse) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{6}
}

func (x *FinalResponse) GetStopReason() StopReason {
	if x != nil {
		return x.StopReason
	}
	return StopReason_STOP_REASON_UNSPECIFIED
}

func (x *FinalResponse) GetUsageMetadata() *UsageMetadata {
	if x != nil {
		return x.UsageMetadata
	}
	return nil
}

// Represents error details (Example structure for field 29)
type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorDetails) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UsageMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PromptTokenCount     int32                  `protobuf:"varint,1,opt,name=prompt_token_count,json=promptTokenCount,proto3" json:"prompt_token_count,omitempty"`
	CandidatesTokenCount int32                  `protobuf:"varint,2,opt,name=candidates_token_count,json=candidatesTokenCount,proto3" json:"candidates_token_count,omitempty"`
	TotalTokenCount      int32                  `protobuf:"varint,3,opt,name=total_token_count,json=totalTokenCount,proto3" json:"total_token_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UsageMetadata) Reset() {
	*x = UsageMetadata{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageMetadata) ProtoMessage() {}

func (x *UsageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageMetadata.ProtoReflect.Descriptor instead.
func (*UsageMetadata) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{8}
}

func (x *UsageMetadata) GetPromptTokenCount() int32 {
	if x != nil {
		return x.PromptTokenCount
	}
	return 0
}

func (x *UsageMetadata) GetCandidatesTokenCount() int32 {
	if x != nil {
		return x.CandidatesTokenCount
	}
	return 0
}

func (x *UsageMetadata) GetTotalTokenCount() int32 {
	if x != nil {
		return x.TotalTokenCount
	}
	return 0
}

type StreamUnifiedChatWithToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestPayload:
	//
	//	*StreamUnifiedChatWithToolsRequest_InitialRequest
	//	*StreamUnifiedChatWithToolsRequest_ToolResult
	//	*StreamUnifiedChatWithToolsRequest_UserMessage
	RequestPayload isStreamUnifiedChatWithToolsRequest_RequestPayload `protobuf_oneof:"request_payload"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamUnifiedChatWithToolsRequest) Reset() {
	*x = StreamUnifiedChatWithToolsRequest{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUnifiedChatWithToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUnifiedChatWithToolsRequest) ProtoMessage() {}

func (x *StreamUnifiedChatWithToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUnifiedChatWithToolsRequest.ProtoReflect.Descriptor instead.
func (*StreamUnifiedChatWithToolsRequest) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{9}
}

func (x *StreamUnifiedChatWithToolsRequest) GetRequestPayload() isStreamUnifiedChatWithToolsRequest_RequestPayload {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *StreamUnifiedChatWithToolsRequest) GetInitialRequest() *InitialRequest {
	if x != nil {
		if x, ok := x.RequestPayload.(*StreamUnifiedChatWithToolsRequest_InitialRequest); ok {
			return x.InitialRequest
		}
	}
	return nil
}

func (x *StreamUnifiedChatWithToolsRequest) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.RequestPayload.(*StreamUnifiedChatWithToolsRequest_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *StreamUnifiedChatWithToolsRequest) GetUserMessage() *UserMessage {
	if x != nil {
		if x, ok := x.RequestPayload.(*StreamUnifiedChatWithToolsRequest_UserMessage); ok {
			return x.UserMessage
		}
	}
	return nil
}

type isStreamUnifiedChatWithToolsRequest_RequestPayload interface {
	isStreamUnifiedChatWithToolsRequest_RequestPayload()
}

type StreamUnifiedChatWithToolsRequest_InitialRequest struct {
	InitialRequest *InitialRequest `protobuf:"bytes,1,opt,name=initial_request,json=initialRequest,proto3,oneof"`
}

type StreamUnifiedChatWithToolsRequest_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,2,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type StreamUnifiedChatWithToolsRequest_UserMessage struct {
	UserMessage *UserMessage `protobuf:"bytes,3,opt,name=user_message,json=userMessage,proto3,oneof"`
}

func (*StreamUnifiedChatWithToolsRequest_InitialRequest) isStreamUnifiedChatWithToolsRequest_RequestPayload() {
}

func (*StreamUnifiedChatWithToolsRequest_ToolResult) isStreamUnifiedChatWithToolsRequest_RequestPayload() {
}

func (*StreamUnifiedChatWithToolsRequest_UserMessage) isStreamUnifiedChatWithToolsRequest_RequestPayload() {
}

type InitialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	ChatSettings  *ChatSettings          `protobuf:"bytes,3,opt,name=chat_settings,json=chatSettings,proto3" json:"chat_settings,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialRequest) Reset() {
	*x = InitialRequest{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialRequest) ProtoMessage() {}

func (x *InitialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialRequest.ProtoReflect.Descriptor instead.
func (*InitialRequest) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{10}
}

func (x *InitialRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InitialRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *InitialRequest) GetChatSettings() *ChatSettings {
	if x != nil {
		return x.ChatSettings
	}
	return nil
}

func (x *InitialRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=aiserver.v1.Role" json:"role,omitempty"`
	Parts         []*RequestContentPart  `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"` // Renamed to avoid conflict if parts differ
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetParts() []*RequestContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*RequestContentPart_Text
	//	*RequestContentPart_Image
	//	*RequestContentPart_Custom
	Part          isRequestContentPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContentPart) Reset() {
	*x = RequestContentPart{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContentPart) ProtoMessage() {}

func (x *RequestContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContentPart.ProtoReflect.Descriptor instead.
func (*RequestContentPart) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{12}
}

func (x *RequestContentPart) GetPart() isRequestContentPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *RequestContentPart) GetText() string {
	if x != nil {
		if x, ok := x.Part.(*RequestContentPart_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *RequestContentPart) GetImage() *Image {
	if x != nil {
		if x, ok := x.Part.(*RequestContentPart_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *RequestContentPart) GetCustom() *structpb.Struct {
	if x != nil {
		if x, ok := x.Part.(*RequestContentPart_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isRequestContentPart_Part interface {
	isRequestContentPart_Part()
}

type RequestContentPart_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type RequestContentPart_Image struct {
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type RequestContentPart_Custom struct {
	Custom *structpb.Struct `protobuf:"bytes,3,opt,name=custom,proto3,oneof"`
}

func (*RequestContentPart_Text) isRequestContentPart_Part() {}

func (*RequestContentPart_Image) isRequestContentPart_Part() {}

func (*RequestContentPart_Custom) isRequestContentPart_Part() {}

type Image struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MimeType string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Image_ImageBytes
	//	*Image_ImageUri
	Data          isImage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{13}
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Image) GetData() isImage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetImageBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*Image_ImageBytes); ok {
			return x.ImageBytes
		}
	}
	return nil
}

func (x *Image) GetImageUri() string {
	if x != nil {
		if x, ok := x.Data.(*Image_ImageUri); ok {
			return x.ImageUri
		}
	}
	return ""
}

type isImage_Data interface {
	isImage_Data()
}

type Image_ImageBytes struct {
	ImageBytes []byte `protobuf:"bytes,2,opt,name=image_bytes,json=imageBytes,proto3,oneof"`
}

type Image_ImageUri struct {
	ImageUri string `protobuf:"bytes,3,opt,name=image_uri,json=imageUri,proto3,oneof"`
}

func (*Image_ImageBytes) isImage_Data() {}

func (*Image_ImageUri) isImage_Data() {}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{14}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

type ChatSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelId         string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Temperature     float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxOutputTokens int32                  `protobuf:"varint,3,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	StopSequences   []string               `protobuf:"bytes,4,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatSettings) Reset() {
	*x = ChatSettings{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSettings) ProtoMessage() {}

func (x *ChatSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSettings.ProtoReflect.Descriptor instead.
func (*ChatSettings) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{15}
}

func (x *ChatSettings) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ChatSettings) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatSettings) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ChatSettings) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

type ToolResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Use Struct for flexibility in tool results, or define specific result types
	Result        *structpb.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	IsError       bool             `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{16}
}

func (x *ToolResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_grpc_server_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_cursor_grpc_server_stream_proto_rawDescGZIP(), []int{17}
}

func (x *UserMessage) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_cursor_grpc_server_stream_proto protoreflect.FileDescriptor

const file_cursor_grpc_server_stream_proto_rawDesc = "" +
	"\n" +
	"\x1fcursor-grpc/server_stream.proto\x12\vaiserver.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"?\n" +
	"\x13GetHardLimitRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\x05H\x00R\x06teamId\x88\x01\x01B\n" +
	"\n" +
	"\b_team_id\"\x99\x01\n" +
	"\x14GetHardLimitResponse\x12\x1d\n" +
	"\n" +
	"hard_limit\x18\x01 \x01(\x05R\thardLimit\x123\n" +
	"\x16no_usage_based_allowed\x18\x02 \x01(\bR\x13noUsageBasedAllowed\x12-\n" +
	"\x13hard_limit_per_user\x18\x03 \x01(\x05R\x10hardLimitPerUser\"S\n" +
	"\"StreamUnifiedChatWithToolsResponse\x12-\n" +
	"\x04part\x18\x02 \x01(\v2\x19.aiserver.v1.ResponsePartR\x04part\"\xf7\x02\n" +
	"\fResponsePart\x12A\n" +
	"\x0fmetadata_marker\x18\x17 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0emetadataMarker\x12\x1d\n" +
	"\tbubble_id\x18\x1b \x01(\tH\x00R\bbubbleId\x12=\n" +
	"\fmessage_part\x18\x19 \x01(\v2\x18.aiserver.v1.ContentPartH\x00R\vmessagePart\x124\n" +
	"\ttool_call\x18\x1a \x01(\v2\x15.aiserver.v1.ToolCallH\x00R\btoolCall\x12C\n" +
	"\x0efinal_response\x18\x1c \x01(\v2\x1a.aiserver.v1.FinalResponseH\x00R\rfinalResponse\x12@\n" +
	"\rerror_details\x18\x1d \x01(\v2\x19.aiserver.v1.ErrorDetailsH\x00R\ferrorDetailsB\t\n" +
	"\acontent\"V\n" +
	"\vContentPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x80\x01\n" +
	"\bToolCall\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\"\x8c\x01\n" +
	"\rFinalResponse\x128\n" +
	"\vstop_reason\x18\x01 \x01(\x0e2\x17.aiserver.v1.StopReasonR\n" +
	"stopReason\x12A\n" +
	"\x0eusage_metadata\x18\x02 \x01(\v2\x1a.aiserver.v1.UsageMetadataR\rusageMetadata\"<\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\rUsageMetadata\x12,\n" +
	"\x12prompt_token_count\x18\x01 \x01(\x05R\x10promptTokenCount\x124\n" +
	"\x16candidates_token_count\x18\x02 \x01(\x05R\x14candidatesTokenCount\x12*\n" +
	"\x11total_token_count\x18\x03 \x01(\x05R\x0ftotalTokenCount\"\xf9\x01\n" +
	"!StreamUnifiedChatWithToolsRequest\x12F\n" +
	"\x0finitial_request\x18\x01 \x01(\v2\x1b.aiserver.v1.InitialRequestH\x00R\x0einitialRequest\x12:\n" +
	"\vtool_result\x18\x02 \x01(\v2\x17.aiserver.v1.ToolResultH\x00R\n" +
	"toolResult\x12=\n" +
	"\fuser_message\x18\x03 \x01(\v2\x18.aiserver.v1.UserMessageH\x00R\vuserMessageB\x11\n" +
	"\x0frequest_payload\"\xe4\x01\n" +
	"\x0eInitialRequest\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.aiserver.v1.ChatMessageR\bmessages\x12'\n" +
	"\x05tools\x18\x02 \x03(\v2\x11.aiserver.v1.ToolR\x05tools\x12>\n" +
	"\rchat_settings\x18\x03 \x01(\v2\x19.aiserver.v1.ChatSettingsR\fchatSettings\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xa1\x01\n" +
	"\vChatMessage\x12%\n" +
	"\x04role\x18\x01 \x01(\x0e2\x11.aiserver.v1.RoleR\x04role\x125\n" +
	"\x05parts\x18\x02 \x03(\v2\x1f.aiserver.v1.RequestContentPartR\x05parts\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x91\x01\n" +
	"\x12RequestContentPart\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12*\n" +
	"\x05image\x18\x02 \x01(\v2\x12.aiserver.v1.ImageH\x00R\x05image\x121\n" +
	"\x06custom\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\x06customB\x06\n" +
	"\x04part\"n\n" +
	"\x05Image\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12!\n" +
	"\vimage_bytes\x18\x02 \x01(\fH\x00R\n" +
	"imageBytes\x12\x1d\n" +
	"\timage_uri\x18\x03 \x01(\tH\x00R\bimageUriB\x06\n" +
	"\x04data\"x\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\"\x9e\x01\n" +
	"\fChatSettings\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12*\n" +
	"\x11max_output_tokens\x18\x03 \x01(\x05R\x0fmaxOutputTokens\x12%\n" +
	"\x0estop_sequences\x18\x04 \x03(\tR\rstopSequences\"z\n" +
	"\n" +
	"ToolResult\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"A\n" +
	"\vUserMessage\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.aiserver.v1.ChatMessageR\amessage*{\n" +
	"\n" +
	"StopReason\x12\x1b\n" +
	"\x17STOP_REASON_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTOP_SEQUENCE\x10\x01\x12\x0e\n" +
	"\n" +
	"MAX_TOKENS\x10\x02\x12\f\n" +
	"\bTOOL_USE\x10\x03\x12\x14\n" +
	"\x10CONTENT_FILTERED\x10\x04\x12\t\n" +
	"\x05OTHER\x10\x05*K\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tASSISTANT\x10\x02\x12\b\n" +
	"\x04TOOL\x10\x03\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x042g\n" +
	"\x10DashboardService\x12S\n" +
	"\fGetHardLimit\x12 .aiserver.v1.GetHardLimitRequest\x1a!.aiserver.v1.GetHardLimitResponse2\x9b\x01\n" +
	"\x12UnifiedChatService\x12\x84\x01\n" +
	"\x1dStreamUnifiedChatWithToolsSSE\x12..aiserver.v1.StreamUnifiedChatWithToolsRequest\x1a/.aiserver.v1.StreamUnifiedChatWithToolsResponse(\x010\x01B$Z\"github.com/mcp-gateway/cursor-grpcb\x06proto3"

var (
	file_cursor_grpc_server_stream_proto_rawDescOnce sync.Once
	file_cursor_grpc_server_stream_proto_rawDescData []byte
)

func file_cursor_grpc_server_stream_proto_rawDescGZIP() []byte {
	file_cursor_grpc_server_stream_proto_rawDescOnce.Do(func() {
		file_cursor_grpc_server_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_grpc_server_stream_proto_rawDesc), len(file_cursor_grpc_server_stream_proto_rawDesc)))
	})
	return file_cursor_grpc_server_stream_proto_rawDescData
}

var file_cursor_grpc_server_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cursor_grpc_server_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cursor_grpc_server_stream_proto_goTypes = []any{
	(StopReason)(0),                            // 0: aiserver.v1.StopReason
	(Role)(0),                                  // 1: aiserver.v1.Role
	(*GetHardLimitRequest)(nil),                // 2: aiserver.v1.GetHardLimitRequest
	(*GetHardLimitResponse)(nil),               // 3: aiserver.v1.GetHardLimitResponse
	(*StreamUnifiedChatWithToolsResponse)(nil), // 4: aiserver.v1.StreamUnifiedChatWithToolsResponse
	(*ResponsePart)(nil),                       // 5: aiserver.v1.ResponsePart
	(*ContentPart)(nil),                        // 6: aiserver.v1.ContentPart
	(*ToolCall)(nil),                           // 7: aiserver.v1.ToolCall
	(*FinalResponse)(nil),                      // 8: aiserver.v1.FinalResponse
	(*ErrorDetails)(nil),                       // 9: aiserver.v1.ErrorDetails
	(*UsageMetadata)(nil),                      // 10: aiserver.v1.UsageMetadata
	(*StreamUnifiedChatWithToolsRequest)(nil),  // 11: aiserver.v1.StreamUnifiedChatWithToolsRequest
	(*InitialRequest)(nil),                     // 12: aiserver.v1.InitialRequest
	(*ChatMessage)(nil),                        // 13: aiserver.v1.ChatMessage
	(*RequestContentPart)(nil),                 // 14: aiserver.v1.RequestContentPart
	(*Image)(nil),                              // 15: aiserver.v1.Image
	(*Tool)(nil),                               // 16: aiserver.v1.Tool
	(*ChatSettings)(nil),                       // 17: aiserver.v1.ChatSettings
	(*ToolResult)(nil),                         // 18: aiserver.v1.ToolResult
	(*UserMessage)(nil),                        // 19: aiserver.v1.UserMessage
	(*emptypb.Empty)(nil),                      // 20: google.protobuf.Empty
	(*structpb.Struct)(nil),                    // 21: google.protobuf.Struct
}
var file_cursor_grpc_server_stream_proto_depIdxs = []int32{
	5,  // 0: aiserver.v1.StreamUnifiedChatWithToolsResponse.part:type_name -> aiserver.v1.ResponsePart
	20, // 1: aiserver.v1.ResponsePart.metadata_marker:type_name -> google.protobuf.Empty
	6,  // 2: aiserver.v1.ResponsePart.message_part:type_name -> aiserver.v1.ContentPart
	7,  // 3: aiserver.v1.ResponsePart.tool_call:type_name -> aiserver.v1.ToolCall
	8,  // 4: aiserver.v1.ResponsePart.final_response:type_name -> aiserver.v1.FinalResponse
	9,  // 5: aiserver.v1.ResponsePart.error_details:type_name -> aiserver.v1.ErrorDetails
	21, // 6: aiserver.v1.ContentPart.metadata:type_name -> google.protobuf.Struct
	21, // 7: aiserver.v1.ToolCall.arguments:type_name -> google.protobuf.Struct
	0,  // 8: aiserver.v1.FinalResponse.stop_reason:type_name -> aiserver.v1.StopReason
	10, // 9: aiserver.v1.FinalResponse.usage_metadata:type_name -> aiserver.v1.UsageMetadata
	12, // 10: aiserver.v1.StreamUnifiedChatWithToolsRequest.initial_request:type_name -> aiserver.v1.InitialRequest
	18, // 11: aiserver.v1.StreamUnifiedChatWithToolsRequest.tool_result:type_name -> aiserver.v1.ToolResult
	19, // 12: aiserver.v1.StreamUnifiedChatWithToolsRequest.user_message:type_name -> aiserver.v1.UserMessage
	13, // 13: aiserver.v1.InitialRequest.messages:type_name -> aiserver.v1.ChatMessage
	16, // 14: aiserver.v1.InitialRequest.tools:type_name -> aiserver.v1.Tool
	17, // 15: aiserver.v1.InitialRequest.chat_settings:type_name -> aiserver.v1.ChatSettings
	21, // 16: aiserver.v1.InitialRequest.metadata:type_name -> google.protobuf.Struct
	1,  // 17: aiserver.v1.ChatMessage.role:type_name -> aiserver.v1.Role
	14, // 18: aiserver.v1.ChatMessage.parts:type_name -> aiserver.v1.RequestContentPart
	15, // 19: aiserver.v1.RequestContentPart.image:type_name -> aiserver.v1.Image
	21, // 20: aiserver.v1.RequestContentPart.custom:type_name -> google.protobuf.Struct
	21, // 21: aiserver.v1.Tool.input_schema:type_name -> google.protobuf.Struct
	21, // 22: aiserver.v1.ToolResult.result:type_name -> google.protobuf.Struct
	13, // 23: aiserver.v1.UserMessage.message:type_name -> aiserver.v1.ChatMessage
	2,  // 24: aiserver.v1.DashboardService.GetHardLimit:input_type -> aiserver.v1.GetHardLimitRequest
	11, // 25: aiserver.v1.UnifiedChatService.StreamUnifiedChatWithToolsSSE:input_type -> aiserver.v1.StreamUnifiedChatWithToolsRequest
	3,  // 26: aiserver.v1.DashboardService.GetHardLimit:output_type -> aiserver.v1.GetHardLimitResponse
	4,  // 27: aiserver.v1.UnifiedChatService.StreamUnifiedChatWithToolsSSE:output_type -> aiserver.v1.StreamUnifiedChatWithToolsResponse
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_cursor_grpc_server_stream_proto_init() }
func file_cursor_grpc_server_stream_proto_init() {
	if File_cursor_grpc_server_stream_proto != nil {
		return
	}
	file_cursor_grpc_server_stream_proto_msgTypes[0].OneofWrappers = []any{}
	file_cursor_grpc_server_stream_proto_msgTypes[3].OneofWrappers = []any{
		(*ResponsePart_MetadataMarker)(nil),
		(*ResponsePart_BubbleId)(nil),
		(*ResponsePart_MessagePart)(nil),
		(*ResponsePart_ToolCall)(nil),
		(*ResponsePart_FinalResponse)(nil),
		(*ResponsePart_ErrorDetails)(nil),
	}
	file_cursor_grpc_server_stream_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamUnifiedChatWithToolsRequest_InitialRequest)(nil),
		(*StreamUnifiedChatWithToolsRequest_ToolResult)(nil),
		(*StreamUnifiedChatWithToolsRequest_UserMessage)(nil),
	}
	file_cursor_grpc_server_stream_proto_msgTypes[12].OneofWrappers = []any{
		(*RequestContentPart_Text)(nil),
		(*RequestContentPart_Image)(nil),
		(*RequestContentPart_Custom)(nil),
	}
	file_cursor_grpc_server_stream_proto_msgTypes[13].OneofWrappers = []any{
		(*Image_ImageBytes)(nil),
		(*Image_ImageUri)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_grpc_server_stream_proto_rawDesc), len(file_cursor_grpc_server_stream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cursor_grpc_server_stream_proto_goTypes,
		DependencyIndexes: file_cursor_grpc_server_stream_proto_depIdxs,
		EnumInfos:         file_cursor_grpc_server_stream_proto_enumTypes,
		MessageInfos:      file_cursor_grpc_server_stream_proto_msgTypes,
	}.Build()
	File_cursor_grpc_server_stream_proto = out.File
	file_cursor_grpc_server_stream_proto_goTypes = nil
	file_cursor_grpc_server_stream_proto_depIdxs = nil
}
