// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: internal/policy/ml/proto/dlp_inference.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DLPInference_DetectSensitiveInfo_FullMethodName      = "/dlp_inference.DLPInference/DetectSensitiveInfo"
	DLPInference_BatchDetectSensitiveInfo_FullMethodName = "/dlp_inference.DLPInference/BatchDetectSensitiveInfo"
	DLPInference_HealthCheck_FullMethodName              = "/dlp_inference.DLPInference/HealthCheck"
)

// DLPInferenceClient is the client API for DLPInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DLPInferenceClient interface {
	DetectSensitiveInfo(ctx context.Context, in *SensitiveInfoRequest, opts ...grpc.CallOption) (*SensitiveInfoResponse, error)
	BatchDetectSensitiveInfo(ctx context.Context, in *BatchSensitiveInfoRequest, opts ...grpc.CallOption) (*BatchSensitiveInfoResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dLPInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewDLPInferenceClient(cc grpc.ClientConnInterface) DLPInferenceClient {
	return &dLPInferenceClient{cc}
}

func (c *dLPInferenceClient) DetectSensitiveInfo(ctx context.Context, in *SensitiveInfoRequest, opts ...grpc.CallOption) (*SensitiveInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensitiveInfoResponse)
	err := c.cc.Invoke(ctx, DLPInference_DetectSensitiveInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dLPInferenceClient) BatchDetectSensitiveInfo(ctx context.Context, in *BatchSensitiveInfoRequest, opts ...grpc.CallOption) (*BatchSensitiveInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSensitiveInfoResponse)
	err := c.cc.Invoke(ctx, DLPInference_BatchDetectSensitiveInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dLPInferenceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DLPInference_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DLPInferenceServer is the server API for DLPInference service.
// All implementations must embed UnimplementedDLPInferenceServer
// for forward compatibility.
type DLPInferenceServer interface {
	DetectSensitiveInfo(context.Context, *SensitiveInfoRequest) (*SensitiveInfoResponse, error)
	BatchDetectSensitiveInfo(context.Context, *BatchSensitiveInfoRequest) (*BatchSensitiveInfoResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDLPInferenceServer()
}

// UnimplementedDLPInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDLPInferenceServer struct{}

func (UnimplementedDLPInferenceServer) DetectSensitiveInfo(context.Context, *SensitiveInfoRequest) (*SensitiveInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectSensitiveInfo not implemented")
}
func (UnimplementedDLPInferenceServer) BatchDetectSensitiveInfo(context.Context, *BatchSensitiveInfoRequest) (*BatchSensitiveInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDetectSensitiveInfo not implemented")
}
func (UnimplementedDLPInferenceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDLPInferenceServer) mustEmbedUnimplementedDLPInferenceServer() {}
func (UnimplementedDLPInferenceServer) testEmbeddedByValue()                      {}

// UnsafeDLPInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DLPInferenceServer will
// result in compilation errors.
type UnsafeDLPInferenceServer interface {
	mustEmbedUnimplementedDLPInferenceServer()
}

func RegisterDLPInferenceServer(s grpc.ServiceRegistrar, srv DLPInferenceServer) {
	// If the following call pancis, it indicates UnimplementedDLPInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DLPInference_ServiceDesc, srv)
}

func _DLPInference_DetectSensitiveInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensitiveInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DLPInferenceServer).DetectSensitiveInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DLPInference_DetectSensitiveInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DLPInferenceServer).DetectSensitiveInfo(ctx, req.(*SensitiveInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DLPInference_BatchDetectSensitiveInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSensitiveInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DLPInferenceServer).BatchDetectSensitiveInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DLPInference_BatchDetectSensitiveInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DLPInferenceServer).BatchDetectSensitiveInfo(ctx, req.(*BatchSensitiveInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DLPInference_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DLPInferenceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DLPInference_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DLPInferenceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DLPInference_ServiceDesc is the grpc.ServiceDesc for DLPInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DLPInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dlp_inference.DLPInference",
	HandlerType: (*DLPInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectSensitiveInfo",
			Handler:    _DLPInference_DetectSensitiveInfo_Handler,
		},
		{
			MethodName: "BatchDetectSensitiveInfo",
			Handler:    _DLPInference_BatchDetectSensitiveInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DLPInference_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/policy/ml/proto/dlp_inference.proto",
}
