// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/policy/ml/proto/dlp_inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_policy_ml_proto_dlp_inference_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_internal_policy_ml_proto_dlp_inference_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{6, 0}
}

type SensitiveInfoRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Text                string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId           string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Categories          []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`                                                // 탐지할 카테고리 필터
	IncludeReasoning    bool                   `protobuf:"varint,5,opt,name=include_reasoning,json=includeReasoning,proto3" json:"include_reasoning,omitempty"`           // AI 추론 과정 포함 여부
	ConfidenceThreshold float32                `protobuf:"fixed32,6,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"` // 신뢰도 임계값
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SensitiveInfoRequest) Reset() {
	*x = SensitiveInfoRequest{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveInfoRequest) ProtoMessage() {}

func (x *SensitiveInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveInfoRequest.ProtoReflect.Descriptor instead.
func (*SensitiveInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SensitiveInfoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SensitiveInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SensitiveInfoRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SensitiveInfoRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SensitiveInfoRequest) GetIncludeReasoning() bool {
	if x != nil {
		return x.IncludeReasoning
	}
	return false
}

func (x *SensitiveInfoRequest) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

type SensitiveInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Detections       []*SensitiveDetection  `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	ConfidenceScore  float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ModelVersion     string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	RequestId        string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromCache        bool                   `protobuf:"varint,6,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SensitiveInfoResponse) Reset() {
	*x = SensitiveInfoResponse{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveInfoResponse) ProtoMessage() {}

func (x *SensitiveInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveInfoResponse.ProtoReflect.Descriptor instead.
func (*SensitiveInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{1}
}

func (x *SensitiveInfoResponse) GetDetections() []*SensitiveDetection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *SensitiveInfoResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *SensitiveInfoResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *SensitiveInfoResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *SensitiveInfoResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SensitiveInfoResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type SensitiveDetection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	StartPosition int32                  `protobuf:"varint,4,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition   int32                  `protobuf:"varint,5,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning     string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"` // AI가 왜 이렇게 판단했는지 설명
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`       // 탐지 소스 (regex/ml/hybrid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensitiveDetection) Reset() {
	*x = SensitiveDetection{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveDetection) ProtoMessage() {}

func (x *SensitiveDetection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveDetection.ProtoReflect.Descriptor instead.
func (*SensitiveDetection) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{2}
}

func (x *SensitiveDetection) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SensitiveDetection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SensitiveDetection) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SensitiveDetection) GetStartPosition() int32 {
	if x != nil {
		return x.StartPosition
	}
	return 0
}

func (x *SensitiveDetection) GetEndPosition() int32 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

func (x *SensitiveDetection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SensitiveDetection) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *SensitiveDetection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BatchSensitiveInfoRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Requests       []*SensitiveInfoRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	BatchTimeoutMs int32                   `protobuf:"varint,2,opt,name=batch_timeout_ms,json=batchTimeoutMs,proto3" json:"batch_timeout_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchSensitiveInfoRequest) Reset() {
	*x = BatchSensitiveInfoRequest{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSensitiveInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSensitiveInfoRequest) ProtoMessage() {}

func (x *BatchSensitiveInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSensitiveInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchSensitiveInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSensitiveInfoRequest) GetRequests() []*SensitiveInfoRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchSensitiveInfoRequest) GetBatchTimeoutMs() int32 {
	if x != nil {
		return x.BatchTimeoutMs
	}
	return 0
}

type BatchSensitiveInfoResponse struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	Responses             []*SensitiveInfoResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalProcessingTimeMs int64                    `protobuf:"varint,2,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	SuccessfulRequests    int32                    `protobuf:"varint,3,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests        int32                    `protobuf:"varint,4,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BatchSensitiveInfoResponse) Reset() {
	*x = BatchSensitiveInfoResponse{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSensitiveInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSensitiveInfoResponse) ProtoMessage() {}

func (x *BatchSensitiveInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSensitiveInfoResponse.ProtoReflect.Descriptor instead.
func (*BatchSensitiveInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{4}
}

func (x *BatchSensitiveInfoResponse) GetResponses() []*SensitiveInfoResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchSensitiveInfoResponse) GetTotalProcessingTimeMs() int64 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

func (x *BatchSensitiveInfoResponse) GetSuccessfulRequests() int32 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *BatchSensitiveInfoResponse) GetFailedRequests() int32 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dlp_inference.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_policy_ml_proto_dlp_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_policy_ml_proto_dlp_inference_proto protoreflect.FileDescriptor

const file_internal_policy_ml_proto_dlp_inference_proto_rawDesc = "" +
	"\n" +
	",internal/policy/ml/proto/dlp_inference.proto\x12\rdlp_inference\"\xe2\x01\n" +
	"\x14SensitiveInfoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12+\n" +
	"\x11include_reasoning\x18\x05 \x01(\bR\x10includeReasoning\x121\n" +
	"\x14confidence_threshold\x18\x06 \x01(\x02R\x13confidenceThreshold\"\x96\x02\n" +
	"\x15SensitiveInfoResponse\x12A\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2!.dlp_inference.SensitiveDetectionR\n" +
	"detections\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x06 \x01(\bR\tfromCache\"\xfa\x01\n" +
	"\x12SensitiveDetection\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12%\n" +
	"\x0estart_position\x18\x04 \x01(\x05R\rstartPosition\x12!\n" +
	"\fend_position\x18\x05 \x01(\x05R\vendPosition\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\x86\x01\n" +
	"\x19BatchSensitiveInfoRequest\x12?\n" +
	"\brequests\x18\x01 \x03(\v2#.dlp_inference.SensitiveInfoRequestR\brequests\x12(\n" +
	"\x10batch_timeout_ms\x18\x02 \x01(\x05R\x0ebatchTimeoutMs\"\xf3\x01\n" +
	"\x1aBatchSensitiveInfoResponse\x12B\n" +
	"\tresponses\x18\x01 \x03(\v2$.dlp_inference.SensitiveInfoResponseR\tresponses\x127\n" +
	"\x18total_processing_time_ms\x18\x02 \x01(\x03R\x15totalProcessingTimeMs\x12/\n" +
	"\x13successful_requests\x18\x03 \x01(\x05R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x04 \x01(\x05R\x0efailedRequests\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xd3\x01\n" +
	"\x13HealthCheckResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.dlp_inference.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xb7\x02\n" +
	"\fDLPInference\x12`\n" +
	"\x13DetectSensitiveInfo\x12#.dlp_inference.SensitiveInfoRequest\x1a$.dlp_inference.SensitiveInfoResponse\x12o\n" +
	"\x18BatchDetectSensitiveInfo\x12(.dlp_inference.BatchSensitiveInfoRequest\x1a).dlp_inference.BatchSensitiveInfoResponse\x12T\n" +
	"\vHealthCheck\x12!.dlp_inference.HealthCheckRequest\x1a\".dlp_inference.HealthCheckResponseB&Z$mcp-gateway/internal/policy/ml/protob\x06proto3"

var (
	file_internal_policy_ml_proto_dlp_inference_proto_rawDescOnce sync.Once
	file_internal_policy_ml_proto_dlp_inference_proto_rawDescData []byte
)

func file_internal_policy_ml_proto_dlp_inference_proto_rawDescGZIP() []byte {
	file_internal_policy_ml_proto_dlp_inference_proto_rawDescOnce.Do(func() {
		file_internal_policy_ml_proto_dlp_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_policy_ml_proto_dlp_inference_proto_rawDesc), len(file_internal_policy_ml_proto_dlp_inference_proto_rawDesc)))
	})
	return file_internal_policy_ml_proto_dlp_inference_proto_rawDescData
}

var file_internal_policy_ml_proto_dlp_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_policy_ml_proto_dlp_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_policy_ml_proto_dlp_inference_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: dlp_inference.HealthCheckResponse.ServingStatus
	(*SensitiveInfoRequest)(nil),           // 1: dlp_inference.SensitiveInfoRequest
	(*SensitiveInfoResponse)(nil),          // 2: dlp_inference.SensitiveInfoResponse
	(*SensitiveDetection)(nil),             // 3: dlp_inference.SensitiveDetection
	(*BatchSensitiveInfoRequest)(nil),      // 4: dlp_inference.BatchSensitiveInfoRequest
	(*BatchSensitiveInfoResponse)(nil),     // 5: dlp_inference.BatchSensitiveInfoResponse
	(*HealthCheckRequest)(nil),             // 6: dlp_inference.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 7: dlp_inference.HealthCheckResponse
}
var file_internal_policy_ml_proto_dlp_inference_proto_depIdxs = []int32{
	3, // 0: dlp_inference.SensitiveInfoResponse.detections:type_name -> dlp_inference.SensitiveDetection
	1, // 1: dlp_inference.BatchSensitiveInfoRequest.requests:type_name -> dlp_inference.SensitiveInfoRequest
	2, // 2: dlp_inference.BatchSensitiveInfoResponse.responses:type_name -> dlp_inference.SensitiveInfoResponse
	0, // 3: dlp_inference.HealthCheckResponse.status:type_name -> dlp_inference.HealthCheckResponse.ServingStatus
	1, // 4: dlp_inference.DLPInference.DetectSensitiveInfo:input_type -> dlp_inference.SensitiveInfoRequest
	4, // 5: dlp_inference.DLPInference.BatchDetectSensitiveInfo:input_type -> dlp_inference.BatchSensitiveInfoRequest
	6, // 6: dlp_inference.DLPInference.HealthCheck:input_type -> dlp_inference.HealthCheckRequest
	2, // 7: dlp_inference.DLPInference.DetectSensitiveInfo:output_type -> dlp_inference.SensitiveInfoResponse
	5, // 8: dlp_inference.DLPInference.BatchDetectSensitiveInfo:output_type -> dlp_inference.BatchSensitiveInfoResponse
	7, // 9: dlp_inference.DLPInference.HealthCheck:output_type -> dlp_inference.HealthCheckResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_policy_ml_proto_dlp_inference_proto_init() }
func file_internal_policy_ml_proto_dlp_inference_proto_init() {
	if File_internal_policy_ml_proto_dlp_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_policy_ml_proto_dlp_inference_proto_rawDesc), len(file_internal_policy_ml_proto_dlp_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_policy_ml_proto_dlp_inference_proto_goTypes,
		DependencyIndexes: file_internal_policy_ml_proto_dlp_inference_proto_depIdxs,
		EnumInfos:         file_internal_policy_ml_proto_dlp_inference_proto_enumTypes,
		MessageInfos:      file_internal_policy_ml_proto_dlp_inference_proto_msgTypes,
	}.Build()
	File_internal_policy_ml_proto_dlp_inference_proto = out.File
	file_internal_policy_ml_proto_dlp_inference_proto_goTypes = nil
	file_internal_policy_ml_proto_dlp_inference_proto_depIdxs = nil
}
