# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dlp_inference_pb2 as dlp__inference__pb2


class DLPInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectSensitiveInfo = channel.unary_unary(
                '/dlp_inference.DLPInference/DetectSensitiveInfo',
                request_serializer=dlp__inference__pb2.SensitiveInfoRequest.SerializeToString,
                response_deserializer=dlp__inference__pb2.SensitiveInfoResponse.FromString,
                )
        self.BatchDetectSensitiveInfo = channel.unary_unary(
                '/dlp_inference.DLPInference/BatchDetectSensitiveInfo',
                request_serializer=dlp__inference__pb2.BatchSensitiveInfoRequest.SerializeToString,
                response_deserializer=dlp__inference__pb2.BatchSensitiveInfoResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/dlp_inference.DLPInference/HealthCheck',
                request_serializer=dlp__inference__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=dlp__inference__pb2.HealthCheckResponse.FromString,
                )


class DLPInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectSensitiveInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDetectSensitiveInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DLPInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectSensitiveInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSensitiveInfo,
                    request_deserializer=dlp__inference__pb2.SensitiveInfoRequest.FromString,
                    response_serializer=dlp__inference__pb2.SensitiveInfoResponse.SerializeToString,
            ),
            'BatchDetectSensitiveInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDetectSensitiveInfo,
                    request_deserializer=dlp__inference__pb2.BatchSensitiveInfoRequest.FromString,
                    response_serializer=dlp__inference__pb2.BatchSensitiveInfoResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=dlp__inference__pb2.HealthCheckRequest.FromString,
                    response_serializer=dlp__inference__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dlp_inference.DLPInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DLPInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectSensitiveInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dlp_inference.DLPInference/DetectSensitiveInfo',
            dlp__inference__pb2.SensitiveInfoRequest.SerializeToString,
            dlp__inference__pb2.SensitiveInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchDetectSensitiveInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dlp_inference.DLPInference/BatchDetectSensitiveInfo',
            dlp__inference__pb2.BatchSensitiveInfoRequest.SerializeToString,
            dlp__inference__pb2.BatchSensitiveInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dlp_inference.DLPInference/HealthCheck',
            dlp__inference__pb2.HealthCheckRequest.SerializeToString,
            dlp__inference__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
